### ISSUE TITLE
Include dependencies with SystemJS

### ISSUE THREAD

**Issue by bes1002t** [fintechneo/angular2-templates#1]
You are using Jspm and Jspm could use SystemJS to include dependencies inside your index.html. Why are you not using the built in SystemJS to include dependencies in your index.html?

**Comment by petersalomonsen** [comment]
JSPM/SystemJS is only used for the development environment (index_dev.html), while the production environment (index.html) is using an Ahead-Of-Time compiled bundle ( https://angular.io/docs/ts/latest/cookbook/aot-compiler.html ). So no SystemJS/JSPM is needed in prod since everything is in the bundle file.

Did it answer your question? Makes sense?

**Comment by bes1002t** [comment]
yes totally, thank you :)
